<?php

namespace AppBundle\Repository;

/**
 * NeoDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeoDataRepository extends \Doctrine\ORM\EntityRepository
{
	public function getHazardousAsteroid()
	{
        	$query =  $this->getEntityManager()
            		->createQuery("SELECT neo_data FROM 
            				AppBundle\Entity\NeoData neo_data");
            		
            	return $query->getArrayResult();
    	}

    	public function getFastestAsteroid($bool)
	{
        	$query = $this->getEntityManager()
            		->createQuery("SELECT neo_data  FROM 
            				AppBundle\Entity\NeoData neo_data WHERE
            			 	neo_data.isHazardous = :ishazardous ORDER BY neo_data.speed DESC")
            		->setParameter('ishazardous', $bool)
            		->setMaxResults(1);

            	return $query->getArrayResult();
    	}

    	public function getAsteroidYears($bool)
	{
        	$query = $this->getEntityManager()
            		->createQuery("SELECT SUBSTRING(neo_data.date,1,4) as year FROM 
            				AppBundle\Entity\NeoData neo_data WHERE
            			 	neo_data.isHazardous = :ishazardous ORDER BY neo_data.date DESC")
            		->setParameter('ishazardous', $bool);
            		
            	return $query->getArrayResult();
    	}

    	public function getAsteroidMonths($bool)
	{
        	$query = $this->getEntityManager()
            		->createQuery("SELECT SUBSTRING(neo_data.date,6,2) as month FROM 
            				AppBundle\Entity\NeoData neo_data WHERE
            			 	neo_data.isHazardous = :ishazardous ORDER BY neo_data.date DESC")
            		->setParameter('ishazardous', $bool);
            		
            	return $query->getArrayResult();
    	}
}
